export const ROUTES = {
  home: "/",
  shop: "/shop",
  services: "/services",
  doneForYou: "/done-for-you",
  about: "/about",
  faq: "/faq",
  contact: "/contact",
  cart: "/cart",
  checkout: "/checkout",
  thankYou: "/thank-you",

  account: "/account",
  orders: "/orders",
  downloads: "/downloads",
  requests: "/requests",

  admin: "/admin",
  adminProducts: "/admin/products",
  adminServices: "/admin/services",
  adminOrders: "/admin/orders",
  adminCustomers: "/admin/customers",
  adminRequests: "/admin/requests",
  adminDeliveries: "/admin/deliveries",
  adminAnalytics: "/admin/analytics",
} as const;